name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: https://oxygenos.oneplus.net/OnePlus7ProOxygen_21.P.27_OTA_027_all_2005192132_e3185c1907734508.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: OxygenOS-Helios
  TZ: Middle-East/Kuwait

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python-dev
            sudo -E apt-get -qq install python
            sudo -E apt-get -qq install simg2img
            sudo -E apt-get -qq install python-protobuf
            python --version

       
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/JamieHoSzeYui/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
                        
       - name: downloading the firmware
         run: curl -O https://oxygenos.oneplus.net/OnePlus7ProOxygen_21.P.27_OTA_027_all_2005192132_e3185c1907734508.zip ErfanGSIs
       - name: removing system
         run: sudo umount system && sudo rm -r system
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/dynamic.sh $ROM_NAME ErfanGSIs/OnePlus7ProOxygen_21.P.27_OTA_027_all_2005192132_e3185c1907734508.zip
      
       - name: making dir
         run: sudo mkdir oos
       
       - name: mounting the system
         run: sudo mount ErfanGSIs/cache/system.img oos
       - name: making the gsi
         run: sudo ./ErfanGSIs/url2GSI.sh ErfanGSIs/cache/oos $ROM_NAME
       
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
             
       - name: uploading Aonly.zip
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer cow ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z 
                       
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: uploading AB.zip
         run: |
              ./transfer cow ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer cow ErfanGSIs/output/*-Aonly-*.txt
         

                                                  

  
         
     
