name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:
  ROM_URL: https://oxygenos.oneplus.net/NordOxygen_14_OTA_005_all_2007312151_d1f7295e1ae8422e.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: OxygenOS-Helios
  TZ: Middle-East/Kuwait

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the workflow 
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python-dev
            sudo -E apt-get -qq install python
            sudo -E apt-get -qq install simg2img
            sudo -E apt-get -qq install python-protobuf
            python --version

       
       - name: processing ErfanGSIs code 
         run: git clone --recurse-submodules https://github.com/adamayyad/ErfanGSIs.git
       
       - name: Setting up requirements and permissions
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
                        
       - name: downloading the firmware
         run: sudo wget $ROM_URL -P ErfanGSIs
      
     
       - name: using zip2img.sh 
         run: sudo ./ErfanGSIs/zip2img.sh ErfanGSIs/NordOxygen_14_OTA_005_all_2007312151_d1f7295e1ae8422e.zip
       - name: cloning ext4extract
         run: git clone https://github.com/erfanoabdi/ext4extract.git 
       - name: moving to ext4extract
         run: sudo mv ErfanGSIs/cache/system.img ext4extract
       - name: making outputfile
         run: cd ext4extract && sudo mkdir outputfile
       - name: runninng the script
         run: sudo LC_CTYPE=C.UTF-8 python3 ext4extract/ext4extract.py -D ext4extract/outputfile ext4extract/system.img
       - name: add prep 1
         run: cd ext4extract && ls && sudo mount -o ro system.img outputfile
       - name: sudo su
         run: sudo su 
       - name: add prep 2
         run: cd ext4extract && dd if=/dev/zero of=system_new.img bs=4k count=1048576 && mkfs.ext4 system_new.img && tune2fs -c0 -i0 system_new.img            
       - name: add pep3
         run: cd ext4extract && sudo mkdir system_new && sudo mount -o loop system_new.img system_new
       - name: final command
         run: cd ext4extract && sudo cp -v -r -p outputfile/* system_new/ && sync  
       - name: using make.sh 
         run: sudo ./ErfanGSIs/make.sh ext4extract/system_new $ROM_NAME AB && sudo ./ErfanGSIs/make.sh ext4extract/system_new $ROM_NAME Aonly
         
     
       - name: Zipping Aonly
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/out
              zip -r ErfanGSIs/out/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/out/*-Aonly-*.img
             
       - name: uploading Aonly.zip
         run: |    
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof ErfanGSIs/out/$ZIP_NAME-GSI-Aonly.7z 
                       
       - name: Zipping AB
         run: |
              zip -r ErfanGSIs/out/$ZIP_NAME-GSI-AB.7z ErfanGSIs/out/*-AB-*.img
              
       - name: uploading AB.zip
         run: |
              ./transfer gof ErfanGSIs/out/$ZIP_NAME-GSI-AB.7z      
              
       - name: Upload Build Informations and Baked:)
         run: |
              ./transfer gof ErfanGSIs/out/*-Aonly-*.txt
         

                                                  

  
         
     
