name: Time to Bake...

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]

      
    
env:              #change ROM_URL,ROM_NAME,ZIP_NAME,ROMZIP_NAME respectivley. ROM_NAME is case sensitive 
  ROM_URL: https://otafsg1.h2os.com/patch/amazone2/GLO/NordOxygen/NordOxygen_14.O.10_GLO_010_2009260504/NordOxygen_14.O.10_OTA_010_all_2009260504_113aafee5.zip
  ROMZIP_NAME: NordOxygen_14.O.10_OTA_010_all_2009260504_113aafee5.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: OxygenOS-HELIOS-07-10
  SECRETS_PASSWORD: ${{ secrets.SFGPASS }}
  TZ: Middle-East/Kuwait
  SFDIRA1: cd /home/pfs/project/helios-gsis/HeliosBakery
  SFDIRA2: cd /home/pfs/project/helios-gsis/Heliosbakerybills
  SFMAIL: ${{ secrets.SFMAIL }}
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the SPICES and its SPICES
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt install expect -y
            
       - name: CONFIGURING HBT
         run: |
           expect -c " 
           spawn git clone --recurse-submodules ${{ secrets.super }} ErfanGSIs
           expect \"Username\"             
           send \"${{ secrets.superuser }}\r\"
           expect \"Password\"          
           send \"${{ secrets.superpassword }}\r\""
           set timeout -1
           interact"
           sudo chmod -R 777 ErfanGSIs
           cd ErfanGSIs
           sudo bash setup.sh 
        
       - name: DOWNLOADING THE FIRMWARE
         run: |
           cd ErfanGSIs && sudo wget $ROM_URL 
       
       - name: GENERATION OF BAKED GOODIES
         run: |
            cd ErfanGSIs && sudo ./dyn.sh $ROM_NAME $ROMZIP_NAME && sudo umount system && sudo rm -rf system
            
       - name: MOUNTING THE SYSTEM
         run: |
           cd ErfanGSIs/cache && sudo mkdir dynamic && sudo mount -o ro system.img dynamic 
         
       - name: MAKING THE COOKIES
         run: | 
           cd ErfanGSIs && sudo ./make.sh cache/dynamic $ROM_NAME AB && sudo ./make.sh cache/dynamic $ROM_NAME Aonly  
       
       - name: Zipping BOTH COOKIES
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/out
              zip -r ErfanGSIs/out/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/out/*-Aonly-*.img 
              zip -r ErfanGSIs/out/$ZIP_NAME-GSI-AB.7z ErfanGSIs/out/*-AB-*.img
              
       - name: uploading to HELIOSBAKERY
         run: |   
              cd ErfanGSIs/out
              expect -c " 
              spawn sftp $SFMAIL
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA2\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp $SFMAIL
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp $SFMAIL
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"  
