name: TIME TO BAKE .......

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - main
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: SETTING UP THE SPICES
         run: |
           sudo apt install expect -y
           sudo apt install python3
           sudo -E apt-get -qq update
           sudo -E apt-get -qq install simg2img
      
       - name: CONFIGURING HBT
         run: |
           expect -c " 
           spawn git clone ${{ secrets.GHID }} ErfanGSIs
           expect \"Username\"        
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -1
           catch wait result
           interact"
           sudo chmod -R 777 ErfanGSIs
           cd ErfanGSIs
           sudo bash setup.sh           
           
