name: Time to Bake...
on: 
  #releasepush:
    #pushbuild
  watch: 
      types: [started]
#######################   CHANGE ONLY ROM_URL,ROM_NAME,FIRMWAREZIPANEM,ZIPNAME,SCRIPT_NAME  ###################################
env:
  ROM_URL: https://tdrive.ridhinabraham.workers.dev//miui_GRAMINGlobal_V12.0.1.0.QJPINXM_be860b8c30_10.0.zip
  ROM_NAME: MIUI
  FIRMWAREZIPNAME: miui_GRAMINGlobal_V12.0.1.0.QJPINXM_be860b8c30_10.0.zip
  ZIP_NAME: MIUIPOCO-HELIOS-21-10
  SCRIPT_NAME: NUBIA-VOS-MIUIDP
  SECRETS_PASSWORD: ${{ secrets.SFGPASS }}
  TZ: Middle-East/Kuwait
  SFDIRA1: cd /home/pfs/project/helios-gsis/HeliosBakery
  SFDIRA2: cd /home/pfs/project/helios-gsis/Heliosbakerybills
  
jobs:
    build:
       runs-on: ubuntu-latest
    
    
       steps:
        - name: Checkout
          uses: actions/checkout@main
       
           
        - name: Setting up the SPICES and its SPICES
          run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt-get install -y expect
            git clone --recurse-submodules ${{ secrets.TOPSECRET }} ErfanGSIs
            sudo chmod -R 777 ErfanGSIs
            cd ErfanGSIs
            sudo bash setup.sh
            
        - name: DOWNLOADING THE FIRMWARE
          run: cd ErfanGSIs && sudo wget $ROM_URL 
          
        - name: GENERATION OF BAKED GOODIES
          run: | 
            cd ErfanGSIs && sudo ./$SCRIPT_NAME.sh $ROM_NAME $FIRMWAREZIPNAME && sudo umount system && sudo rm -rf system
            
            
        - name: MOUNTING THE SYSTEM
          run: cd ErfanGSIs/cache && sudo mkdir dynamic && sudo mount -o ro system.img dynamic 
         
        - name: MAKING THE COOKIES
          run: cd ErfanGSIs && sudo ./url2GSI.sh cache/dynamic $ROM_NAME  
       
        - name: Zipping BOTH COOKIES
          run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img 
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
        - name: uploading to HELIOSBAKERY
          run: |   
              cd ErfanGSIs/output
              expect -c " 
              spawn sftp ridhin@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA2\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp ridhin@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp ridhin@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"  
